hacf-fr/lovelace-meteofrance-weather-card

dist/weather-card.js
=> Fix displayed wind direction when undefined

dist/meteofrance-weather-card-editor.js, dist/meteofrance-weather-card.js
La configuration de l'affichage du forecast en heure ou jour est géré automatiquement
Suivant le delta des deux 1er forecast, si c'est > 24h alors daily, sinon hourly!
=> Autodetect hourly or daily forecast

LICENSE
Ajout de l'auteur 'imbuzi' pour la reprise de certaine partie de son code et HACF pour la participation communautaire sur cette carte.
=> Modification du copyright

README.md, info.md
Ajout de la méthode d'installation et configuration via YAML dans la documentation.
=> Ajout de YAML dans la documentation

README.md, info.md
- Précision des fonctionnalités.
- Réorganisation des titres.
=> Amélioration de la documentation

dist/meteofrance-weather-card.js
- Titre sur deux lignes (temps actuel + détails)
- Ajout d'un nouveaux sensor au choix en détail.
- Adapte le texte de la météo actuel pour éviter le chevauchement du texte.
- Traduction du temps actuel pour l'affichage.
Code à vérifier, voir si mes traductions sont judicieuses, les positionnements ext.
=> Changement du haut de la carte 1/2

dist/meteofrance-weather-card-editor.js
Ajout le choix du capteur pour afficher en détail sur le haut de la carte.
=> Changement du haut de la carte 2/2

dist/meteofrance-weather-card.js
A voir si cela peut être mieux fais.
=> ajout "Pas de valeur" pour rainForecastValues.

dist/meteofrance-weather-card.js
* Refonte du CSS avec l'uniformisation de l'usage du positionnement flex (fix #16)
* Modification de texte de certains phénomènes en corrélation avec ce que propose Météo France
* Déclaration des entités à l'initialisation de la carte (fix #31 )
=> Refonte du CSS

dist/meteofrance-weather-card.js
* Refonte du CSS (en flex)
* Suppression dernier trait dans forecast
* Modification de terme de prévision
* Correction placement dans une alerte
* Ajout texte d'annonce de pluie à venir
=> Refonte CSS et corrections diverses

dist/meteofrance-weather-card.js
L'événement d'update prend maintenant en compte la mise à jour des données des sensors (avant uniquement l'entité weather).
=> Bugfix : prise en compte de la maj des sensors

dist/meteofrance-weather-card.js
Positionne la température sur le titre à droite.
=> Temperature du titre à droite

dist/meteofrance-weather-card.js
meteo france 5,10,15,20,25,30,40 50 et pas 5,10,15,20,25,35,45,55
=> fix #19 : Mise en conformité texte et legende pour ressembler au site

dist/meteofrance-weather-card.js
C'est une base de travail ... je ne suis pas un pro de l'UI  ... du coup n'hesitez pas à ajouter des espaces ou rendre ca plus aéré / Joli ...
=> Changement d'affichage pour les alertes

README.md, dist/meteofrance-weather-card.js
=> Ajout possibilité de masquer certaines icones d'alerte

README.md
Mise à jour de la procédure pour mieux coller à l'interface d'HACS qui a un peu changé depuis l'écriture de cette procédure.
=> Mise à jour de l'interface de HACS

dist/meteofrance-weather-card.js
Adds wind speed to the hourly forecast. 
At present this is misisng from the implementation
Below an example of the enhancement, note that the post-sunset icons are fixed in a separate PR
=> Add windspeed to forecast

README.md, dist/meteofrance-weather-card.js
Remove multiplication of 3.6 to adhere to standard unit: km/h
=> Fix incorrect re-calculation of wind_speed in forecast

dist/meteofrance-weather-card-editor.js
Fix load ha-entity-selector for editor
=> Fix load ha-entity-selector for editor

dist/meteofrance-weather-card-editor.js
Fix load ha-entity-selector for editor
**Rattrapage vers la branche dev**
=> Fix load ha-entity-selector for editor (#119)

README.md
Allows to add the repository to HACS and jump directly to step 3 when installing.
=> Add My.home-assistant.io link and fix a little typo

hacs.json
=> Add hacs.json to allow download via HACS 2.0

dist/meteofrance-weather-card.js
-Added horizontal scrollbar for hourly and daily mesures
-Updated daily column with day-month, 
-Updated hourly column with weekday-day
-Set column size to 8ch to improve visibility when precipitation is 2 digits like "22.5 mm"
=> Horizontal scroll for daily & hourly
